// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i8KuCHvKrwawZpBmyovrv7
// Component: 0HdNPwUwApqj
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import PageLayout from "../../PageLayout"; // plasmic-import: hH7MsQQ-bd8u/component
import { AntdRadio } from "@plasmicpkgs/antd5/skinny/registerRadio";
import WeddingPhotographyBlogCard from "../../WeddingPhotographyBlogCard"; // plasmic-import: qBUXaaiW1Dkm/component
import EmailSubscription from "../../EmailSubscription"; // plasmic-import: 8K23kVTVNTsQ/component
import { useScreenVariants as useScreenVariantszapf5SksSeNd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZAPF5sksSeNd/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: i8KuCHvKrwawZpBmyovrv7/projectcss
import sty from "./PlasmicBlogListing.module.css"; // plasmic-import: 0HdNPwUwApqj/css
import Search1Icon from "./icons/PlasmicIcon__Search1"; // plasmic-import: k1ZxOywolUMa/icon
import ArrowIcon from "./icons/PlasmicIcon__Arrow"; // plasmic-import: CXu4c-n_ggmp/icon
import Line3Icon from "./icons/PlasmicIcon__Line3"; // plasmic-import: BBAKPheFo4LH/icon

createPlasmicElementProxy;

export const PlasmicBlogListing__VariantProps = new Array();

export const PlasmicBlogListing__ArgProps = new Array();

const $$ = {};

function PlasmicBlogListing__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszapf5SksSeNd()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          />

          <div className={classNames(projectcss.all, sty.freeBox___7StbV)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame1000005968"}
              data-plasmic-override={overrides.frame1000005968}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame1000005968)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"field"}
                data-plasmic-override={overrides.field}
                hasGap={true}
                className={classNames(projectcss.all, sty.field)}
              >
                <div
                  data-plasmic-name={"search"}
                  data-plasmic-override={overrides.search}
                  className={classNames(projectcss.all, sty.search)}
                >
                  <div
                    data-plasmic-name={"group365"}
                    data-plasmic-override={overrides.group365}
                    className={classNames(projectcss.all, sty.group365)}
                  >
                    <Search1Icon
                      className={classNames(projectcss.all, sty.svg__cJHyY)}
                      role={"img"}
                    />
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__z071
                  )}
                >
                  {"Search For Blogs"}
                </div>
              </Stack__>
              <div
                data-plasmic-name={"frame1000005975"}
                data-plasmic-override={overrides.frame1000005975}
                className={classNames(projectcss.all, sty.frame1000005975)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__nopkb
                  )}
                >
                  {"Blogs Categories"}
                </div>
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame1000005965"}
                data-plasmic-override={overrides.frame1000005965}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1000005965)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1000005964"}
                  data-plasmic-override={overrides.frame1000005964}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1000005964)}
                >
                  <AntdRadio
                    data-plasmic-name={"component3"}
                    data-plasmic-override={overrides.component3}
                    className={classNames("__wab_instance", sty.component3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gy9Zc
                      )}
                    >
                      {""}
                    </div>
                  </AntdRadio>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ltvA
                    )}
                  >
                    {"Photography / Videography"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1000005963"}
                  data-plasmic-override={overrides.frame1000005963}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1000005963)}
                >
                  <AntdRadio
                    data-plasmic-name={"component2"}
                    data-plasmic-override={overrides.component2}
                    className={classNames("__wab_instance", sty.component2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aaOyT
                      )}
                    >
                      {""}
                    </div>
                  </AntdRadio>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__c2RHm
                    )}
                  >
                    {"Beauty"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1000005966"}
                  data-plasmic-override={overrides.frame1000005966}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1000005966)}
                >
                  <AntdRadio
                    data-plasmic-name={"component4"}
                    data-plasmic-override={overrides.component4}
                    className={classNames("__wab_instance", sty.component4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qi82O
                      )}
                    >
                      {""}
                    </div>
                  </AntdRadio>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xqAU
                    )}
                  >
                    {"Wedding Dress"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1000005967"}
                  data-plasmic-override={overrides.frame1000005967}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1000005967)}
                >
                  <AntdRadio
                    data-plasmic-name={"component5"}
                    data-plasmic-override={overrides.component5}
                    className={classNames("__wab_instance", sty.component5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hkmb7
                      )}
                    >
                      {""}
                    </div>
                  </AntdRadio>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zW2Th
                    )}
                  >
                    {"Food"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1000005969"}
                  data-plasmic-override={overrides.frame1000005969}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1000005969)}
                >
                  <AntdRadio
                    data-plasmic-name={"component6"}
                    data-plasmic-override={overrides.component6}
                    className={classNames("__wab_instance", sty.component6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fXvym
                      )}
                    >
                      {""}
                    </div>
                  </AntdRadio>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__usRwu
                    )}
                  >
                    {"Horoscope"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1000005970"}
                  data-plasmic-override={overrides.frame1000005970}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1000005970)}
                >
                  <AntdRadio
                    data-plasmic-name={"component7"}
                    data-plasmic-override={overrides.component7}
                    className={classNames("__wab_instance", sty.component7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xpVu0
                      )}
                    >
                      {""}
                    </div>
                  </AntdRadio>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pRiZ
                    )}
                  >
                    {"Entertainment"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame1000005971"}
                  data-plasmic-override={overrides.frame1000005971}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame1000005971)}
                >
                  <AntdRadio
                    data-plasmic-name={"component8"}
                    data-plasmic-override={overrides.component8}
                    className={classNames("__wab_instance", sty.component8)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aerub
                      )}
                    >
                      {""}
                    </div>
                  </AntdRadio>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eiCnY
                    )}
                  >
                    {"Magazine"}
                  </div>
                </Stack__>
              </Stack__>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__esv80)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__t6XZn)}
              >
                <div
                  data-plasmic-name={"breadcrumb"}
                  data-plasmic-override={overrides.breadcrumb}
                  className={classNames(projectcss.all, sty.breadcrumb)}
                >
                  <div
                    data-plasmic-name={"linkButton"}
                    data-plasmic-override={overrides.linkButton}
                    className={classNames(projectcss.all, sty.linkButton)}
                  >
                    <div
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.button
                      )}
                    >
                      {"Home"}
                    </div>
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pqFn
                    )}
                  >
                    {"Blog"}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gTuls
                    )}
                  >
                    {"Photography / Videography"}
                  </div>
                  <ArrowIcon
                    className={classNames(projectcss.all, sty.svg__p7RuU)}
                    role={"img"}
                  />

                  <ArrowIcon
                    className={classNames(projectcss.all, sty.svg__aO24V)}
                    role={"img"}
                  />
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xtGhm
                  )}
                >
                  {"Photography & Videography"}
                </div>
              </Stack__>
              <div
                data-plasmic-name={"group375"}
                data-plasmic-override={overrides.group375}
                className={classNames(projectcss.all, sty.group375)}
              >
                <div
                  data-plasmic-name={"rectangle28"}
                  data-plasmic-override={overrides.rectangle28}
                  className={classNames(projectcss.all, sty.rectangle28)}
                />

                <div
                  data-plasmic-name={"rectangle29"}
                  data-plasmic-override={overrides.rectangle29}
                  className={classNames(projectcss.all, sty.rectangle29)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qjzB5
                  )}
                >
                  {"Photography"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uWr4
                  )}
                >
                  {
                    "2024 Style Guide: \nUnveiling the Hottest Fashion and Lifestyle Brands"
                  }
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"profile"}
                  data-plasmic-override={overrides.profile}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.profile)}
                >
                  <div
                    data-plasmic-name={"profile2"}
                    data-plasmic-override={overrides.profile2}
                    className={classNames(projectcss.all, sty.profile2)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6C74F
                    )}
                  >
                    {"Kiran"}
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d9SrG
                  )}
                >
                  {"Wed 14, 2024"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mDdAi
                  )}
                >
                  {
                    "In 2024, the world of fashion and lifestyle brands is evolving at a rapid pace, offering consumers an array of exciting options to explore."
                  }
                </div>
                <div
                  data-plasmic-name={"linkButtonLarge"}
                  data-plasmic-override={overrides.linkButtonLarge}
                  className={classNames(projectcss.all, sty.linkButtonLarge)}
                >
                  <div
                    data-plasmic-name={"button2"}
                    data-plasmic-override={overrides.button2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button2
                    )}
                  >
                    {"Read More"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"frame1000006070"}
                  data-plasmic-override={overrides.frame1000006070}
                  className={classNames(projectcss.all, sty.frame1000006070)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__gZmZx)}
                    displayHeight={"72px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"72px"}
                    loading={"lazy"}
                    src={{
                      src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MiA3MiI+CiAgPHBhdGggZmlsbD0iIzY2NiIgZD0iTTAgMGg3MnY3MkgweiIvPgogIDxwYXRoIGQ9Ik00MCAyOGwtOCA4IDggOCIgc3Ryb2tlPSIjZmZmIiBzdHJva2UtbGluZWNhcD0icm91bmQiLz4KPC9zdmc+Cg==",
                      fullWidth: 72,
                      fullHeight: 72,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__iY5Kg)}
                    displayHeight={"72px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"72px"}
                    loading={"lazy"}
                    src={{
                      src: "data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MiA3MiI+CiAgPHBhdGggZmlsbD0iIzY2NiIgZD0iTTAgMGg3MnY3MkgweiIvPgogIDxwYXRoIGQ9Ik0zMiAyOGw4IDgtOCA4IiBzdHJva2U9IiNmZmYiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIvPgo8L3N2Zz4K",
                      fullWidth: 72,
                      fullHeight: 72,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"group374"}
                data-plasmic-override={overrides.group374}
                hasGap={true}
                className={classNames(projectcss.all, sty.group374)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wtc2W)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard___3RLsA
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__kfO4L
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__aqn8W
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__wOxo)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__mswb1
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__n0X9Z
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard___0ILl4
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__q62LC)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__bTrAe
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__e4IXm
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__vqKhN
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__kcqOn)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__kQs8
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__zhUt8
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__qR8HW
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__e97L)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__um1Qa
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__lfF
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__r3Bjp
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__upcC2)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__baHe4
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__qHlR8
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard___3LKdc
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__oxXDq)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__nteNa
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__dsbmh
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__elJOs
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__t5Oko)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__mqWQx
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__zhlUn
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__dQdxs
                    )}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__lbyu3)}>
                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__xkeEh
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard__nvzE
                    )}
                  />

                  <WeddingPhotographyBlogCard
                    className={classNames(
                      "__wab_instance",
                      sty.weddingPhotographyBlogCard___4TTi
                    )}
                  />
                </div>
              </Stack__>
            </div>
          </div>
          <div
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"footerCards"}
              data-plasmic-override={overrides.footerCards}
              hasGap={true}
              className={classNames(projectcss.all, sty.footerCards)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___83Nv1
                )}
              >
                {
                  "Thank you for choosing Wedding Vows to be part of your extraordinary journey. As you embark on this beautiful adventure of love, may your vows become the foundation of a lifetime filled with joy, understanding, and countless cherished moments. Our commitment is to make every step of your wedding journey memorable, ensuring that your celebration reflects the uniqueness of your love story. Feel the warmth of our support, the creativity of our services, and the dedication of our team. Your moments are precious, and we're honoured to be a part of them."
                }
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame1000005943"}
                data-plasmic-override={overrides.frame1000005943}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1000005943)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card"}
                  data-plasmic-override={overrides.card}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000005932"}
                    data-plasmic-override={overrides.frame1000005932}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000005932)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h2Ce
                      )}
                    >
                      {"Contact us to get best deals"}
                    </div>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"frame1000005931"}
                      data-plasmic-override={overrides.frame1000005931}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.frame1000005931
                      )}
                    >
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame1000005929"}
                        data-plasmic-override={overrides.frame1000005929}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.frame1000005929
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___6YrhL
                          )}
                        >
                          {"For Vendors"}
                        </div>
                        <div
                          data-plasmic-name={"linkButton21"}
                          data-plasmic-override={overrides.linkButton21}
                          className={classNames(
                            projectcss.all,
                            sty.linkButton21
                          )}
                        >
                          <div
                            data-plasmic-name={"button22"}
                            data-plasmic-override={overrides.button22}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.button22
                            )}
                          >
                            {"vendors@wedding.com"}
                          </div>
                        </div>
                      </Stack__>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__z7DBi
                        )}
                      >
                        <Line3Icon
                          className={classNames(projectcss.all, sty.svg__oypcf)}
                          role={"img"}
                        />
                      </div>
                      <Stack__
                        as={"div"}
                        data-plasmic-name={"frame1000005930"}
                        data-plasmic-override={overrides.frame1000005930}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.frame1000005930
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yod
                          )}
                        >
                          {"For Users"}
                        </div>
                        <div
                          data-plasmic-name={"linkButton2"}
                          data-plasmic-override={overrides.linkButton2}
                          className={classNames(
                            projectcss.all,
                            sty.linkButton2
                          )}
                        >
                          <div
                            data-plasmic-name={"button23"}
                            data-plasmic-override={overrides.button23}
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.button23
                            )}
                          >
                            {"info@wedding.com"}
                          </div>
                        </div>
                      </Stack__>
                    </Stack__>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000005933"}
                    data-plasmic-override={overrides.frame1000005933}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000005933)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9Lo3V
                      )}
                    >
                      {"Newsletter & Magazine Subscriptions"}
                    </div>
                    <EmailSubscription
                      data-plasmic-name={"emailSubscription"}
                      data-plasmic-override={overrides.emailSubscription}
                      className={classNames(
                        "__wab_instance",
                        sty.emailSubscription
                      )}
                    />
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card2"}
                  data-plasmic-override={overrides.card2}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___341Hn
                    )}
                  >
                    {"Start Planning"}
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000005935"}
                    data-plasmic-override={overrides.frame1000005935}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000005935)}
                  >
                    <div
                      data-plasmic-name={"linkButton3"}
                      data-plasmic-override={overrides.linkButton3}
                      className={classNames(projectcss.all, sty.linkButton3)}
                    >
                      <div
                        data-plasmic-name={"button4"}
                        data-plasmic-override={overrides.button4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button4
                        )}
                      >
                        {"Search By Vendor"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton4"}
                      data-plasmic-override={overrides.linkButton4}
                      className={classNames(projectcss.all, sty.linkButton4)}
                    >
                      <div
                        data-plasmic-name={"button5"}
                        data-plasmic-override={overrides.button5}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button5
                        )}
                      >
                        {"Search By City"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton5"}
                      data-plasmic-override={overrides.linkButton5}
                      className={classNames(projectcss.all, sty.linkButton5)}
                    >
                      <div
                        data-plasmic-name={"button6"}
                        data-plasmic-override={overrides.button6}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button6
                        )}
                      >
                        {"Top Rated Vendors"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton6"}
                      data-plasmic-override={overrides.linkButton6}
                      className={classNames(projectcss.all, sty.linkButton6)}
                    >
                      <div
                        data-plasmic-name={"button7"}
                        data-plasmic-override={overrides.button7}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button7
                        )}
                      >
                        {"Destination Wedding"}
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card3"}
                  data-plasmic-override={overrides.card3}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qWeFq
                    )}
                  >
                    {"Wedding Ideas"}
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000005936"}
                    data-plasmic-override={overrides.frame1000005936}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000005936)}
                  >
                    <div
                      data-plasmic-name={"linkButton7"}
                      data-plasmic-override={overrides.linkButton7}
                      className={classNames(projectcss.all, sty.linkButton7)}
                    >
                      <div
                        data-plasmic-name={"button8"}
                        data-plasmic-override={overrides.button8}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button8
                        )}
                      >
                        {"Wedding Blog"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton8"}
                      data-plasmic-override={overrides.linkButton8}
                      className={classNames(projectcss.all, sty.linkButton8)}
                    >
                      <div
                        data-plasmic-name={"button9"}
                        data-plasmic-override={overrides.button9}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button9
                        )}
                      >
                        {"Wedding Inspiration Gallery"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton9"}
                      data-plasmic-override={overrides.linkButton9}
                      className={classNames(projectcss.all, sty.linkButton9)}
                    >
                      <div
                        data-plasmic-name={"button10"}
                        data-plasmic-override={overrides.button10}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button10
                        )}
                      >
                        {"Real Wedding"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton10"}
                      data-plasmic-override={overrides.linkButton10}
                      className={classNames(projectcss.all, sty.linkButton10)}
                    >
                      <div
                        data-plasmic-name={"button11"}
                        data-plasmic-override={overrides.button11}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button11
                        )}
                      >
                        {"Submit Wedding"}
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card4"}
                  data-plasmic-override={overrides.card4}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6KsPb
                    )}
                  >
                    {"Social Links"}
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000005937"}
                    data-plasmic-override={overrides.frame1000005937}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000005937)}
                  >
                    <div
                      data-plasmic-name={"linkButton11"}
                      data-plasmic-override={overrides.linkButton11}
                      className={classNames(projectcss.all, sty.linkButton11)}
                    >
                      <div
                        data-plasmic-name={"button12"}
                        data-plasmic-override={overrides.button12}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button12
                        )}
                      >
                        {"Instagram"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton12"}
                      data-plasmic-override={overrides.linkButton12}
                      className={classNames(projectcss.all, sty.linkButton12)}
                    >
                      <div
                        data-plasmic-name={"button13"}
                        data-plasmic-override={overrides.button13}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button13
                        )}
                      >
                        {"Facebook"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton13"}
                      data-plasmic-override={overrides.linkButton13}
                      className={classNames(projectcss.all, sty.linkButton13)}
                    >
                      <div
                        data-plasmic-name={"button14"}
                        data-plasmic-override={overrides.button14}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button14
                        )}
                      >
                        {"Youtube"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton14"}
                      data-plasmic-override={overrides.linkButton14}
                      className={classNames(projectcss.all, sty.linkButton14)}
                    >
                      <div
                        data-plasmic-name={"button15"}
                        data-plasmic-override={overrides.button15}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button15
                        )}
                      >
                        {"Twitter"}
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"card5"}
                  data-plasmic-override={overrides.card5}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.card5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bhkGl
                    )}
                  >
                    {"Sitemap"}
                  </div>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"frame1000005938"}
                    data-plasmic-override={overrides.frame1000005938}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame1000005938)}
                  >
                    <div
                      data-plasmic-name={"linkButton15"}
                      data-plasmic-override={overrides.linkButton15}
                      className={classNames(projectcss.all, sty.linkButton15)}
                    >
                      <div
                        data-plasmic-name={"button16"}
                        data-plasmic-override={overrides.button16}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button16
                        )}
                      >
                        {"About Wedding Vows"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton16"}
                      data-plasmic-override={overrides.linkButton16}
                      className={classNames(projectcss.all, sty.linkButton16)}
                    >
                      <div
                        data-plasmic-name={"button17"}
                        data-plasmic-override={overrides.button17}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button17
                        )}
                      >
                        {"Careers"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"linkButton17"}
                      data-plasmic-override={overrides.linkButton17}
                      className={classNames(projectcss.all, sty.linkButton17)}
                    >
                      <div
                        data-plasmic-name={"button18"}
                        data-plasmic-override={overrides.button18}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.button18
                        )}
                      >
                        {"Contact Us"}
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"footer2"}
              data-plasmic-override={overrides.footer2}
              hasGap={true}
              className={classNames(projectcss.all, sty.footer2)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jcnky
                )}
              >
                {"\u00a9 2024 | Wedding Vows"}
              </div>
              <Stack__
                as={"div"}
                data-plasmic-name={"frame1000005942"}
                data-plasmic-override={overrides.frame1000005942}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1000005942)}
              >
                <div
                  data-plasmic-name={"linkButton18"}
                  data-plasmic-override={overrides.linkButton18}
                  className={classNames(projectcss.all, sty.linkButton18)}
                >
                  <div
                    data-plasmic-name={"button19"}
                    data-plasmic-override={overrides.button19}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button19
                    )}
                  >
                    {"Terms & Conditions"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"linkButton19"}
                  data-plasmic-override={overrides.linkButton19}
                  className={classNames(projectcss.all, sty.linkButton19)}
                >
                  <div
                    data-plasmic-name={"button20"}
                    data-plasmic-override={overrides.button20}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button20
                    )}
                  >
                    {"Privacy Policy"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"linkButton20"}
                  data-plasmic-override={overrides.linkButton20}
                  className={classNames(projectcss.all, sty.linkButton20)}
                >
                  <div
                    data-plasmic-name={"button21"}
                    data-plasmic-override={overrides.button21}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.button21
                    )}
                  >
                    {"Cancellation Policy"}
                  </div>
                </div>
              </Stack__>
            </Stack__>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageLayout",
    "frame1000005968",
    "field",
    "search",
    "group365",
    "frame1000005975",
    "frame1000005965",
    "frame1000005964",
    "component3",
    "frame1000005963",
    "component2",
    "frame1000005966",
    "component4",
    "frame1000005967",
    "component5",
    "frame1000005969",
    "component6",
    "frame1000005970",
    "component7",
    "frame1000005971",
    "component8",
    "breadcrumb",
    "linkButton",
    "button",
    "group375",
    "rectangle28",
    "rectangle29",
    "profile",
    "profile2",
    "linkButtonLarge",
    "button2",
    "frame1000006070",
    "group374",
    "footer",
    "footerCards",
    "frame1000005943",
    "card",
    "frame1000005932",
    "frame1000005931",
    "frame1000005929",
    "linkButton21",
    "button22",
    "frame1000005930",
    "linkButton2",
    "button23",
    "frame1000005933",
    "emailSubscription",
    "card2",
    "frame1000005935",
    "linkButton3",
    "button4",
    "linkButton4",
    "button5",
    "linkButton5",
    "button6",
    "linkButton6",
    "button7",
    "card3",
    "frame1000005936",
    "linkButton7",
    "button8",
    "linkButton8",
    "button9",
    "linkButton9",
    "button10",
    "linkButton10",
    "button11",
    "card4",
    "frame1000005937",
    "linkButton11",
    "button12",
    "linkButton12",
    "button13",
    "linkButton13",
    "button14",
    "linkButton14",
    "button15",
    "card5",
    "frame1000005938",
    "linkButton15",
    "button16",
    "linkButton16",
    "button17",
    "linkButton17",
    "button18",
    "footer2",
    "frame1000005942",
    "linkButton18",
    "button19",
    "linkButton19",
    "button20",
    "linkButton20",
    "button21"
  ],

  pageLayout: ["pageLayout"],
  frame1000005968: [
    "frame1000005968",
    "field",
    "search",
    "group365",
    "frame1000005975",
    "frame1000005965",
    "frame1000005964",
    "component3",
    "frame1000005963",
    "component2",
    "frame1000005966",
    "component4",
    "frame1000005967",
    "component5",
    "frame1000005969",
    "component6",
    "frame1000005970",
    "component7",
    "frame1000005971",
    "component8"
  ],

  field: ["field", "search", "group365"],
  search: ["search", "group365"],
  group365: ["group365"],
  frame1000005975: ["frame1000005975"],
  frame1000005965: [
    "frame1000005965",
    "frame1000005964",
    "component3",
    "frame1000005963",
    "component2",
    "frame1000005966",
    "component4",
    "frame1000005967",
    "component5",
    "frame1000005969",
    "component6",
    "frame1000005970",
    "component7",
    "frame1000005971",
    "component8"
  ],

  frame1000005964: ["frame1000005964", "component3"],
  component3: ["component3"],
  frame1000005963: ["frame1000005963", "component2"],
  component2: ["component2"],
  frame1000005966: ["frame1000005966", "component4"],
  component4: ["component4"],
  frame1000005967: ["frame1000005967", "component5"],
  component5: ["component5"],
  frame1000005969: ["frame1000005969", "component6"],
  component6: ["component6"],
  frame1000005970: ["frame1000005970", "component7"],
  component7: ["component7"],
  frame1000005971: ["frame1000005971", "component8"],
  component8: ["component8"],
  breadcrumb: ["breadcrumb", "linkButton", "button"],
  linkButton: ["linkButton", "button"],
  button: ["button"],
  group375: [
    "group375",
    "rectangle28",
    "rectangle29",
    "profile",
    "profile2",
    "linkButtonLarge",
    "button2",
    "frame1000006070"
  ],

  rectangle28: ["rectangle28"],
  rectangle29: ["rectangle29"],
  profile: ["profile", "profile2"],
  profile2: ["profile2"],
  linkButtonLarge: ["linkButtonLarge", "button2"],
  button2: ["button2"],
  frame1000006070: ["frame1000006070"],
  group374: ["group374"],
  footer: [
    "footer",
    "footerCards",
    "frame1000005943",
    "card",
    "frame1000005932",
    "frame1000005931",
    "frame1000005929",
    "linkButton21",
    "button22",
    "frame1000005930",
    "linkButton2",
    "button23",
    "frame1000005933",
    "emailSubscription",
    "card2",
    "frame1000005935",
    "linkButton3",
    "button4",
    "linkButton4",
    "button5",
    "linkButton5",
    "button6",
    "linkButton6",
    "button7",
    "card3",
    "frame1000005936",
    "linkButton7",
    "button8",
    "linkButton8",
    "button9",
    "linkButton9",
    "button10",
    "linkButton10",
    "button11",
    "card4",
    "frame1000005937",
    "linkButton11",
    "button12",
    "linkButton12",
    "button13",
    "linkButton13",
    "button14",
    "linkButton14",
    "button15",
    "card5",
    "frame1000005938",
    "linkButton15",
    "button16",
    "linkButton16",
    "button17",
    "linkButton17",
    "button18",
    "footer2",
    "frame1000005942",
    "linkButton18",
    "button19",
    "linkButton19",
    "button20",
    "linkButton20",
    "button21"
  ],

  footerCards: [
    "footerCards",
    "frame1000005943",
    "card",
    "frame1000005932",
    "frame1000005931",
    "frame1000005929",
    "linkButton21",
    "button22",
    "frame1000005930",
    "linkButton2",
    "button23",
    "frame1000005933",
    "emailSubscription",
    "card2",
    "frame1000005935",
    "linkButton3",
    "button4",
    "linkButton4",
    "button5",
    "linkButton5",
    "button6",
    "linkButton6",
    "button7",
    "card3",
    "frame1000005936",
    "linkButton7",
    "button8",
    "linkButton8",
    "button9",
    "linkButton9",
    "button10",
    "linkButton10",
    "button11",
    "card4",
    "frame1000005937",
    "linkButton11",
    "button12",
    "linkButton12",
    "button13",
    "linkButton13",
    "button14",
    "linkButton14",
    "button15",
    "card5",
    "frame1000005938",
    "linkButton15",
    "button16",
    "linkButton16",
    "button17",
    "linkButton17",
    "button18"
  ],

  frame1000005943: [
    "frame1000005943",
    "card",
    "frame1000005932",
    "frame1000005931",
    "frame1000005929",
    "linkButton21",
    "button22",
    "frame1000005930",
    "linkButton2",
    "button23",
    "frame1000005933",
    "emailSubscription",
    "card2",
    "frame1000005935",
    "linkButton3",
    "button4",
    "linkButton4",
    "button5",
    "linkButton5",
    "button6",
    "linkButton6",
    "button7",
    "card3",
    "frame1000005936",
    "linkButton7",
    "button8",
    "linkButton8",
    "button9",
    "linkButton9",
    "button10",
    "linkButton10",
    "button11",
    "card4",
    "frame1000005937",
    "linkButton11",
    "button12",
    "linkButton12",
    "button13",
    "linkButton13",
    "button14",
    "linkButton14",
    "button15",
    "card5",
    "frame1000005938",
    "linkButton15",
    "button16",
    "linkButton16",
    "button17",
    "linkButton17",
    "button18"
  ],

  card: [
    "card",
    "frame1000005932",
    "frame1000005931",
    "frame1000005929",
    "linkButton21",
    "button22",
    "frame1000005930",
    "linkButton2",
    "button23",
    "frame1000005933",
    "emailSubscription"
  ],

  frame1000005932: [
    "frame1000005932",
    "frame1000005931",
    "frame1000005929",
    "linkButton21",
    "button22",
    "frame1000005930",
    "linkButton2",
    "button23"
  ],

  frame1000005931: [
    "frame1000005931",
    "frame1000005929",
    "linkButton21",
    "button22",
    "frame1000005930",
    "linkButton2",
    "button23"
  ],

  frame1000005929: ["frame1000005929", "linkButton21", "button22"],
  linkButton21: ["linkButton21", "button22"],
  button22: ["button22"],
  frame1000005930: ["frame1000005930", "linkButton2", "button23"],
  linkButton2: ["linkButton2", "button23"],
  button23: ["button23"],
  frame1000005933: ["frame1000005933", "emailSubscription"],
  emailSubscription: ["emailSubscription"],
  card2: [
    "card2",
    "frame1000005935",
    "linkButton3",
    "button4",
    "linkButton4",
    "button5",
    "linkButton5",
    "button6",
    "linkButton6",
    "button7"
  ],

  frame1000005935: [
    "frame1000005935",
    "linkButton3",
    "button4",
    "linkButton4",
    "button5",
    "linkButton5",
    "button6",
    "linkButton6",
    "button7"
  ],

  linkButton3: ["linkButton3", "button4"],
  button4: ["button4"],
  linkButton4: ["linkButton4", "button5"],
  button5: ["button5"],
  linkButton5: ["linkButton5", "button6"],
  button6: ["button6"],
  linkButton6: ["linkButton6", "button7"],
  button7: ["button7"],
  card3: [
    "card3",
    "frame1000005936",
    "linkButton7",
    "button8",
    "linkButton8",
    "button9",
    "linkButton9",
    "button10",
    "linkButton10",
    "button11"
  ],

  frame1000005936: [
    "frame1000005936",
    "linkButton7",
    "button8",
    "linkButton8",
    "button9",
    "linkButton9",
    "button10",
    "linkButton10",
    "button11"
  ],

  linkButton7: ["linkButton7", "button8"],
  button8: ["button8"],
  linkButton8: ["linkButton8", "button9"],
  button9: ["button9"],
  linkButton9: ["linkButton9", "button10"],
  button10: ["button10"],
  linkButton10: ["linkButton10", "button11"],
  button11: ["button11"],
  card4: [
    "card4",
    "frame1000005937",
    "linkButton11",
    "button12",
    "linkButton12",
    "button13",
    "linkButton13",
    "button14",
    "linkButton14",
    "button15"
  ],

  frame1000005937: [
    "frame1000005937",
    "linkButton11",
    "button12",
    "linkButton12",
    "button13",
    "linkButton13",
    "button14",
    "linkButton14",
    "button15"
  ],

  linkButton11: ["linkButton11", "button12"],
  button12: ["button12"],
  linkButton12: ["linkButton12", "button13"],
  button13: ["button13"],
  linkButton13: ["linkButton13", "button14"],
  button14: ["button14"],
  linkButton14: ["linkButton14", "button15"],
  button15: ["button15"],
  card5: [
    "card5",
    "frame1000005938",
    "linkButton15",
    "button16",
    "linkButton16",
    "button17",
    "linkButton17",
    "button18"
  ],

  frame1000005938: [
    "frame1000005938",
    "linkButton15",
    "button16",
    "linkButton16",
    "button17",
    "linkButton17",
    "button18"
  ],

  linkButton15: ["linkButton15", "button16"],
  button16: ["button16"],
  linkButton16: ["linkButton16", "button17"],
  button17: ["button17"],
  linkButton17: ["linkButton17", "button18"],
  button18: ["button18"],
  footer2: [
    "footer2",
    "frame1000005942",
    "linkButton18",
    "button19",
    "linkButton19",
    "button20",
    "linkButton20",
    "button21"
  ],

  frame1000005942: [
    "frame1000005942",
    "linkButton18",
    "button19",
    "linkButton19",
    "button20",
    "linkButton20",
    "button21"
  ],

  linkButton18: ["linkButton18", "button19"],
  button19: ["button19"],
  linkButton19: ["linkButton19", "button20"],
  button20: ["button20"],
  linkButton20: ["linkButton20", "button21"],
  button21: ["button21"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBlogListing__ArgProps,
          internalVariantPropNames: PlasmicBlogListing__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBlogListing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBlogListing";
  } else {
    func.displayName = `PlasmicBlogListing.${nodeName}`;
  }
  return func;
}

export const PlasmicBlogListing = Object.assign(
  // Top-level PlasmicBlogListing renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    frame1000005968: makeNodeComponent("frame1000005968"),
    field: makeNodeComponent("field"),
    search: makeNodeComponent("search"),
    group365: makeNodeComponent("group365"),
    frame1000005975: makeNodeComponent("frame1000005975"),
    frame1000005965: makeNodeComponent("frame1000005965"),
    frame1000005964: makeNodeComponent("frame1000005964"),
    component3: makeNodeComponent("component3"),
    frame1000005963: makeNodeComponent("frame1000005963"),
    component2: makeNodeComponent("component2"),
    frame1000005966: makeNodeComponent("frame1000005966"),
    component4: makeNodeComponent("component4"),
    frame1000005967: makeNodeComponent("frame1000005967"),
    component5: makeNodeComponent("component5"),
    frame1000005969: makeNodeComponent("frame1000005969"),
    component6: makeNodeComponent("component6"),
    frame1000005970: makeNodeComponent("frame1000005970"),
    component7: makeNodeComponent("component7"),
    frame1000005971: makeNodeComponent("frame1000005971"),
    component8: makeNodeComponent("component8"),
    breadcrumb: makeNodeComponent("breadcrumb"),
    linkButton: makeNodeComponent("linkButton"),
    button: makeNodeComponent("button"),
    group375: makeNodeComponent("group375"),
    rectangle28: makeNodeComponent("rectangle28"),
    rectangle29: makeNodeComponent("rectangle29"),
    profile: makeNodeComponent("profile"),
    profile2: makeNodeComponent("profile2"),
    linkButtonLarge: makeNodeComponent("linkButtonLarge"),
    button2: makeNodeComponent("button2"),
    frame1000006070: makeNodeComponent("frame1000006070"),
    group374: makeNodeComponent("group374"),
    footer: makeNodeComponent("footer"),
    footerCards: makeNodeComponent("footerCards"),
    frame1000005943: makeNodeComponent("frame1000005943"),
    card: makeNodeComponent("card"),
    frame1000005932: makeNodeComponent("frame1000005932"),
    frame1000005931: makeNodeComponent("frame1000005931"),
    frame1000005929: makeNodeComponent("frame1000005929"),
    linkButton21: makeNodeComponent("linkButton21"),
    button22: makeNodeComponent("button22"),
    frame1000005930: makeNodeComponent("frame1000005930"),
    linkButton2: makeNodeComponent("linkButton2"),
    button23: makeNodeComponent("button23"),
    frame1000005933: makeNodeComponent("frame1000005933"),
    emailSubscription: makeNodeComponent("emailSubscription"),
    card2: makeNodeComponent("card2"),
    frame1000005935: makeNodeComponent("frame1000005935"),
    linkButton3: makeNodeComponent("linkButton3"),
    button4: makeNodeComponent("button4"),
    linkButton4: makeNodeComponent("linkButton4"),
    button5: makeNodeComponent("button5"),
    linkButton5: makeNodeComponent("linkButton5"),
    button6: makeNodeComponent("button6"),
    linkButton6: makeNodeComponent("linkButton6"),
    button7: makeNodeComponent("button7"),
    card3: makeNodeComponent("card3"),
    frame1000005936: makeNodeComponent("frame1000005936"),
    linkButton7: makeNodeComponent("linkButton7"),
    button8: makeNodeComponent("button8"),
    linkButton8: makeNodeComponent("linkButton8"),
    button9: makeNodeComponent("button9"),
    linkButton9: makeNodeComponent("linkButton9"),
    button10: makeNodeComponent("button10"),
    linkButton10: makeNodeComponent("linkButton10"),
    button11: makeNodeComponent("button11"),
    card4: makeNodeComponent("card4"),
    frame1000005937: makeNodeComponent("frame1000005937"),
    linkButton11: makeNodeComponent("linkButton11"),
    button12: makeNodeComponent("button12"),
    linkButton12: makeNodeComponent("linkButton12"),
    button13: makeNodeComponent("button13"),
    linkButton13: makeNodeComponent("linkButton13"),
    button14: makeNodeComponent("button14"),
    linkButton14: makeNodeComponent("linkButton14"),
    button15: makeNodeComponent("button15"),
    card5: makeNodeComponent("card5"),
    frame1000005938: makeNodeComponent("frame1000005938"),
    linkButton15: makeNodeComponent("linkButton15"),
    button16: makeNodeComponent("button16"),
    linkButton16: makeNodeComponent("linkButton16"),
    button17: makeNodeComponent("button17"),
    linkButton17: makeNodeComponent("linkButton17"),
    button18: makeNodeComponent("button18"),
    footer2: makeNodeComponent("footer2"),
    frame1000005942: makeNodeComponent("frame1000005942"),
    linkButton18: makeNodeComponent("linkButton18"),
    button19: makeNodeComponent("button19"),
    linkButton19: makeNodeComponent("linkButton19"),
    button20: makeNodeComponent("button20"),
    linkButton20: makeNodeComponent("linkButton20"),
    button21: makeNodeComponent("button21"),
    // Metadata about props expected for PlasmicBlogListing
    internalVariantProps: PlasmicBlogListing__VariantProps,
    internalArgProps: PlasmicBlogListing__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBlogListing;
/* prettier-ignore-end */
