// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i8KuCHvKrwawZpBmyovrv7
// Component: -enH8ptPHqxi
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  hasVariant,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: i8KuCHvKrwawZpBmyovrv7/projectcss
import sty from "./PlasmicStep2.module.css"; // plasmic-import: -enH8ptPHqxi/css
import SuitcaseSvgrepoComSvgIcon from "./icons/PlasmicIcon__SuitcaseSvgrepoComSvg"; // plasmic-import: AnW24P3guddy/icon
import WhatsappSvgrepoComSvgIcon from "./icons/PlasmicIcon__WhatsappSvgrepoComSvg"; // plasmic-import: p9NwUofQp1Ge/icon
import FileZipperSvgrepoComSvgIcon from "./icons/PlasmicIcon__FileZipperSvgrepoComSvg"; // plasmic-import: 50afEbLn5vwl/icon

createPlasmicElementProxy;

export const PlasmicStep2__VariantProps = new Array("disabled");

export const PlasmicStep2__ArgProps = new Array("stepNumber", "description");

const $$ = {};

function PlasmicStep2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {
          stepNumber: 1,
          description: "Add information"
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "disabled",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.disabled
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={classNames(projectcss.all, sty.freeBox__yjBva, {
          [sty.freeBoxdisabled__yjBva3Rg1G]: hasVariant(
            $state,
            "disabled",
            "disabled"
          )
        })}
      >
        {(() => {
          try {
            return $props.stepNumber === 1;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <SuitcaseSvgrepoComSvgIcon
            className={classNames(projectcss.all, sty.svg___1XEyl, {
              [sty.svgdisabled___1XEyl3Rg1G]: hasVariant(
                $state,
                "disabled",
                "disabled"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(() => {
          try {
            return $props.stepNumber === 2;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <WhatsappSvgrepoComSvgIcon
            className={classNames(projectcss.all, sty.svg__xugLy, {
              [sty.svgdisabled__xugLy3Rg1G]: hasVariant(
                $state,
                "disabled",
                "disabled"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(() => {
          try {
            return $props.stepNumber === 3;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <FileZipperSvgrepoComSvgIcon
            className={classNames(projectcss.all, sty.svg__h66Y, {
              [sty.svgdisabled__h66Y3Rg1G]: hasVariant(
                $state,
                "disabled",
                "disabled"
              )
            })}
            role={"img"}
          />
        ) : null}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__mkInu)}>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__zrwEu,
            {
              [sty.textdisabled__zrwEu3Rg1G]: hasVariant(
                $state,
                "disabled",
                "disabled"
              )
            }
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return "Step " + $props.stepNumber;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__vjWn9,
            {
              [sty.textdisabled__vjWn93Rg1G]: hasVariant(
                $state,
                "disabled",
                "disabled"
              )
            }
          )}
        >
          <React.Fragment>
            {(() => {
              try {
                return $props.description;
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "";
                }
                throw e;
              }
            })()}
          </React.Fragment>
        </div>
      </div>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStep2__ArgProps,
          internalVariantPropNames: PlasmicStep2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStep2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStep2";
  } else {
    func.displayName = `PlasmicStep2.${nodeName}`;
  }
  return func;
}

export const PlasmicStep2 = Object.assign(
  // Top-level PlasmicStep2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicStep2
    internalVariantProps: PlasmicStep2__VariantProps,
    internalArgProps: PlasmicStep2__ArgProps
  }
);

export default PlasmicStep2;
/* prettier-ignore-end */
