// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i8KuCHvKrwawZpBmyovrv7
// Component: 925V5rsjzvih
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: i8KuCHvKrwawZpBmyovrv7/projectcss
import sty from "./PlasmicWeddingPhotographyBlgCard.module.css"; // plasmic-import: 925V5rsjzvih/css

createPlasmicElementProxy;

export const PlasmicWeddingPhotographyBlgCard__VariantProps = new Array();

export const PlasmicWeddingPhotographyBlgCard__ArgProps = new Array();

const $$ = {};

function PlasmicWeddingPhotographyBlgCard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"blogCard"}
      data-plasmic-override={overrides.blogCard}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.blogCard
      )}
    >
      <div
        data-plasmic-name={"imageMask"}
        data-plasmic-override={overrides.imageMask}
        className={classNames(projectcss.all, sty.imageMask)}
      >
        <div
          data-plasmic-name={"image"}
          data-plasmic-override={overrides.image}
          className={classNames(projectcss.all, sty.image)}
        />
      </div>
      <Stack__
        as={"div"}
        data-plasmic-name={"content"}
        data-plasmic-override={overrides.content}
        hasGap={true}
        className={classNames(projectcss.all, sty.content)}
      >
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__rbjH3
          )}
        >
          {"And she said, YES!"}
        </div>
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__p88N0
          )}
        >
          {"Wed 14, 2024"}
        </div>
      </Stack__>
    </Stack__>
  );
}

const PlasmicDescendants = {
  blogCard: ["blogCard", "imageMask", "image", "content"],
  imageMask: ["imageMask", "image"],
  image: ["image"],
  content: ["content"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicWeddingPhotographyBlgCard__ArgProps,
          internalVariantPropNames:
            PlasmicWeddingPhotographyBlgCard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicWeddingPhotographyBlgCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "blogCard") {
    func.displayName = "PlasmicWeddingPhotographyBlgCard";
  } else {
    func.displayName = `PlasmicWeddingPhotographyBlgCard.${nodeName}`;
  }
  return func;
}

export const PlasmicWeddingPhotographyBlgCard = Object.assign(
  // Top-level PlasmicWeddingPhotographyBlgCard renders the root element
  makeNodeComponent("blogCard"),
  {
    // Helper components rendering sub-elements
    imageMask: makeNodeComponent("imageMask"),
    image: makeNodeComponent("image"),
    content: makeNodeComponent("content"),
    // Metadata about props expected for PlasmicWeddingPhotographyBlgCard
    internalVariantProps: PlasmicWeddingPhotographyBlgCard__VariantProps,
    internalArgProps: PlasmicWeddingPhotographyBlgCard__ArgProps
  }
);

export default PlasmicWeddingPhotographyBlgCard;
/* prettier-ignore-end */
