// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i8KuCHvKrwawZpBmyovrv7
// Component: 0UDrNVsjN2gG
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import LayerDefault from "../../LayerDefault"; // plasmic-import: 4uZwDUl-gHmp/component
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: i8KuCHvKrwawZpBmyovrv7/projectcss
import sty from "./PlasmicUserDashboard.module.css"; // plasmic-import: 0UDrNVsjN2gG/css

createPlasmicElementProxy;

export const PlasmicUserDashboard__VariantProps = new Array();

export const PlasmicUserDashboard__ArgProps = new Array();

const $$ = {};

function PlasmicUserDashboard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "countryCode",
        type: "private",
        variableType: "array",
        initFunc: ({ $props, $state, $queries, $ctx }) => [
          { name: "Afghanistan", value: "93", label: "Afghanistan +93" },
          { name: "Aland Islands", value: "358", label: "Aland Islands +358" },
          { name: "Albania", value: "355", label: "Albania +355" },
          { name: "Algeria", value: "213", label: "Algeria +213" },
          {
            name: "AmericanSamoa",
            value: "1684",
            label: "AmericanSamoa +1684"
          },
          { name: "Andorra", value: "376", label: "Andorra +376" },
          { name: "Angola", value: "244", label: "Angola +244" },
          { name: "Anguilla", value: "1264", label: "Anguilla +1264" },
          { name: "Antarctica", value: "672", label: "Antarctica +672" },
          {
            name: "Antigua and Barbuda",
            value: "1268",
            label: "Antigua and Barbuda +1268"
          },
          { name: "Argentina", value: "54", label: "Argentina +54" },
          { name: "Armenia", value: "374", label: "Armenia +374" },
          { name: "Aruba", value: "297", label: "Aruba +297" },
          { name: "Australia", value: "61", label: "Australia +61" },
          { name: "Austria", value: "43", label: "Austria +43" },
          { name: "Azerbaijan", value: "994", label: "Azerbaijan +994" },
          { name: "Bahamas", value: "1242", label: "Bahamas +1242" },
          { name: "Bahrain", value: "973", label: "Bahrain +973" },
          { name: "Bangladesh", value: "880", label: "Bangladesh +880" },
          { name: "Barbados", value: "1246", label: "Barbados +1246" },
          { name: "Belarus", value: "375", label: "Belarus +375" },
          { name: "Belgium", value: "32", label: "Belgium +32" },
          { name: "Belize", value: "501", label: "Belize +501" },
          { name: "Benin", value: "229", label: "Benin +229" },
          { name: "Bermuda", value: "1441", label: "Bermuda +1441" },
          { name: "Bhutan", value: "975", label: "Bhutan +975" },
          {
            name: "Bolivia, Plurinational State of",
            value: "591",
            label: "Bolivia, Plurinational State of +591"
          },
          {
            name: "Bosnia and Herzegovina",
            value: "387",
            label: "Bosnia and Herzegovina +387"
          },
          { name: "Botswana", value: "267", label: "Botswana +267" },
          { name: "Brazil", value: "55", label: "Brazil +55" },
          {
            name: "British Indian Ocean Territory",
            value: "246",
            label: "British Indian Ocean Territory +246"
          },
          {
            name: "Brunei Darussalam",
            value: "673",
            label: "Brunei Darussalam +673"
          },
          { name: "Bulgaria", value: "359", label: "Bulgaria +359" },
          { name: "Burkina Faso", value: "226", label: "Burkina Faso +226" },
          { name: "Burundi", value: "257", label: "Burundi +257" },
          { name: "Cambodia", value: "855", label: "Cambodia +855" },
          { name: "Cameroon", value: "237", label: "Cameroon +237" },
          { name: "Canada", value: "1", label: "Canada +1" },
          { name: "Cape Verde", value: "238", label: "Cape Verde +238" },
          {
            name: "Cayman Islands",
            value: " 345",
            label: "Cayman Islands + 345"
          },
          {
            name: "Central African Republic",
            value: "236",
            label: "Central African Republic +236"
          },
          { name: "Chad", value: "235", label: "Chad +235" },
          { name: "Chile", value: "56", label: "Chile +56" },
          { name: "China", value: "86", label: "China +86" },
          {
            name: "Christmas Island",
            value: "61",
            label: "Christmas Island +61"
          },
          {
            name: "Cocos (Keeling) Islands",
            value: "61",
            label: "Cocos (Keeling) Islands +61"
          },
          { name: "Colombia", value: "57", label: "Colombia +57" },
          { name: "Comoros", value: "269", label: "Comoros +269" },
          { name: "Congo", value: "242", label: "Congo +242" },
          {
            name: "Congo, The Democratic Republic of the Congo",
            value: "243",
            label: "Congo, The Democratic Republic of the Congo +243"
          },
          { name: "Cook Islands", value: "682", label: "Cook Islands +682" },
          { name: "Costa Rica", value: "506", label: "Costa Rica +506" },
          { name: "Cote d'Ivoire", value: "225", label: "Cote d'Ivoire +225" },
          { name: "Croatia", value: "385", label: "Croatia +385" },
          { name: "Cuba", value: "53", label: "Cuba +53" },
          { name: "Cyprus", value: "357", label: "Cyprus +357" },
          {
            name: "Czech Republic",
            value: "420",
            label: "Czech Republic +420"
          },
          { name: "Denmark", value: "45", label: "Denmark +45" },
          { name: "Djibouti", value: "253", label: "Djibouti +253" },
          { name: "Dominica", value: "1767", label: "Dominica +1767" },
          {
            name: "Dominican Republic",
            value: "1849",
            label: "Dominican Republic +1849"
          },
          { name: "Ecuador", value: "593", label: "Ecuador +593" },
          { name: "Egypt", value: "20", label: "Egypt +20" },
          { name: "El Salvador", value: "503", label: "El Salvador +503" },
          {
            name: "Equatorial Guinea",
            value: "240",
            label: "Equatorial Guinea +240"
          },
          { name: "Eritrea", value: "291", label: "Eritrea +291" },
          { name: "Estonia", value: "372", label: "Estonia +372" },
          { name: "Ethiopia", value: "251", label: "Ethiopia +251" },
          {
            name: "Falkland Islands (Malvinas)",
            value: "500",
            label: "Falkland Islands (Malvinas) +500"
          },
          { name: "Faroe Islands", value: "298", label: "Faroe Islands +298" },
          { name: "Fiji", value: "679", label: "Fiji +679" },
          { name: "Finland", value: "358", label: "Finland +358" },
          { name: "France", value: "33", label: "France +33" },
          { name: "French Guiana", value: "594", label: "French Guiana +594" },
          {
            name: "French Polynesia",
            value: "689",
            label: "French Polynesia +689"
          },
          { name: "Gabon", value: "241", label: "Gabon +241" },
          { name: "Gambia", value: "220", label: "Gambia +220" },
          { name: "Georgia", value: "995", label: "Georgia +995" },
          { name: "Germany", value: "49", label: "Germany +49" },
          { name: "Ghana", value: "233", label: "Ghana +233" },
          { name: "Gibraltar", value: "350", label: "Gibraltar +350" },
          { name: "Greece", value: "30", label: "Greece +30" },
          { name: "Greenland", value: "299", label: "Greenland +299" },
          { name: "Grenada", value: "1473", label: "Grenada +1473" },
          { name: "Guadeloupe", value: "590", label: "Guadeloupe +590" },
          { name: "Guam", value: "1671", label: "Guam +1671" },
          { name: "Guatemala", value: "502", label: "Guatemala +502" },
          { name: "Guernsey", value: "44", label: "Guernsey +44" },
          { name: "Guinea", value: "224", label: "Guinea +224" },
          { name: "Guinea-Bissau", value: "245", label: "Guinea-Bissau +245" },
          { name: "Guyana", value: "595", label: "Guyana +595" },
          { name: "Haiti", value: "509", label: "Haiti +509" },
          {
            name: "Holy See (Vatican City State)",
            value: "379",
            label: "Holy See (Vatican City State) +379"
          },
          { name: "Honduras", value: "504", label: "Honduras +504" },
          { name: "Hong Kong", value: "852", label: "Hong Kong +852" },
          { name: "Hungary", value: "36", label: "Hungary +36" },
          { name: "Iceland", value: "354", label: "Iceland +354" },
          { name: "India", value: "91", label: "India +91" },
          { name: "Indonesia", value: "62", label: "Indonesia +62" },
          {
            name: "Iran, Islamic Republic of Persian Gulf",
            value: "98",
            label: "Iran, Islamic Republic of Persian Gulf +98"
          },
          { name: "Iraq", value: "964", label: "Iraq +964" },
          { name: "Ireland", value: "353", label: "Ireland +353" },
          { name: "Isle of Man", value: "44", label: "Isle of Man +44" },
          { name: "Israel", value: "972", label: "Israel +972" },
          { name: "Italy", value: "39", label: "Italy +39" },
          { name: "Jamaica", value: "1876", label: "Jamaica +1876" },
          { name: "Japan", value: "81", label: "Japan +81" },
          { name: "Jersey", value: "44", label: "Jersey +44" },
          { name: "Jordan", value: "962", label: "Jordan +962" },
          { name: "Kazakhstan", value: "77", label: "Kazakhstan +77" },
          { name: "Kenya", value: "254", label: "Kenya +254" },
          { name: "Kiribati", value: "686", label: "Kiribati +686" },
          {
            name: "Korea, Democratic People's Republic of Korea",
            value: "850",
            label: "Korea, Democratic People's Republic of Korea +850"
          },
          {
            name: "Korea, Republic of South Korea",
            value: "82",
            label: "Korea, Republic of South Korea +82"
          },
          { name: "Kuwait", value: "965", label: "Kuwait +965" },
          { name: "Kyrgyzstan", value: "996", label: "Kyrgyzstan +996" },
          { name: "Laos", value: "856", label: "Laos +856" },
          { name: "Latvia", value: "371", label: "Latvia +371" },
          { name: "Lebanon", value: "961", label: "Lebanon +961" },
          { name: "Lesotho", value: "266", label: "Lesotho +266" },
          { name: "Liberia", value: "231", label: "Liberia +231" },
          {
            name: "Libyan Arab Jamahiriya",
            value: "218",
            label: "Libyan Arab Jamahiriya +218"
          },
          { name: "Liechtenstein", value: "423", label: "Liechtenstein +423" },
          { name: "Lithuania", value: "370", label: "Lithuania +370" },
          { name: "Luxembourg", value: "352", label: "Luxembourg +352" },
          { name: "Macao", value: "853", label: "Macao +853" },
          { name: "Macedonia", value: "389", label: "Macedonia +389" },
          { name: "Madagascar", value: "261", label: "Madagascar +261" },
          { name: "Malawi", value: "265", label: "Malawi +265" },
          { name: "Malaysia", value: "60", label: "Malaysia +60" },
          { name: "Maldives", value: "960", label: "Maldives +960" },
          { name: "Mali", value: "223", label: "Mali +223" },
          { name: "Malta", value: "356", label: "Malta +356" },
          {
            name: "Marshall Islands",
            value: "692",
            label: "Marshall Islands +692"
          },
          { name: "Martinique", value: "596", label: "Martinique +596" },
          { name: "Mauritania", value: "222", label: "Mauritania +222" },
          { name: "Mauritius", value: "230", label: "Mauritius +230" },
          { name: "Mayotte", value: "262", label: "Mayotte +262" },
          { name: "Mexico", value: "52", label: "Mexico +52" },
          {
            name: "Micronesia, Federated States of Micronesia",
            value: "691",
            label: "Micronesia, Federated States of Micronesia +691"
          },
          { name: "Moldova", value: "373", label: "Moldova +373" },
          { name: "Monaco", value: "377", label: "Monaco +377" },
          { name: "Mongolia", value: "976", label: "Mongolia +976" },
          { name: "Montenegro", value: "382", label: "Montenegro +382" },
          { name: "Montserrat", value: "1664", label: "Montserrat +1664" },
          { name: "Morocco", value: "212", label: "Morocco +212" },
          { name: "Mozambique", value: "258", label: "Mozambique +258" },
          { name: "Myanmar", value: "95", label: "Myanmar +95" },
          { name: "Namibia", value: "264", label: "Namibia +264" },
          { name: "Nauru", value: "674", label: "Nauru +674" },
          { name: "Nepal", value: "977", label: "Nepal +977" },
          { name: "Netherlands", value: "31", label: "Netherlands +31" },
          {
            name: "Netherlands Antilles",
            value: "599",
            label: "Netherlands Antilles +599"
          },
          { name: "New Caledonia", value: "687", label: "New Caledonia +687" },
          { name: "New Zealand", value: "64", label: "New Zealand +64" },
          { name: "Nicaragua", value: "505", label: "Nicaragua +505" },
          { name: "Niger", value: "227", label: "Niger +227" },
          { name: "Nigeria", value: "234", label: "Nigeria +234" },
          { name: "Niue", value: "683", label: "Niue +683" },
          {
            name: "Norfolk Island",
            value: "672",
            label: "Norfolk Island +672"
          },
          {
            name: "Northern Mariana Islands",
            value: "1670",
            label: "Northern Mariana Islands +1670"
          },
          { name: "Norway", value: "47", label: "Norway +47" },
          { name: "Oman", value: "968", label: "Oman +968" },
          { name: "Pakistan", value: "92", label: "Pakistan +92" },
          { name: "Palau", value: "680", label: "Palau +680" },
          {
            name: "Palestinian Territory, Occupied",
            value: "970",
            label: "Palestinian Territory, Occupied +970"
          },
          { name: "Panama", value: "507", label: "Panama +507" },
          {
            name: "Papua New Guinea",
            value: "675",
            label: "Papua New Guinea +675"
          },
          { name: "Paraguay", value: "595", label: "Paraguay +595" },
          { name: "Peru", value: "51", label: "Peru +51" },
          { name: "Philippines", value: "63", label: "Philippines +63" },
          { name: "Pitcairn", value: "872", label: "Pitcairn +872" },
          { name: "Poland", value: "48", label: "Poland +48" },
          { name: "Portugal", value: "351", label: "Portugal +351" },
          { name: "Puerto Rico", value: "1939", label: "Puerto Rico +1939" },
          { name: "Qatar", value: "974", label: "Qatar +974" },
          { name: "Romania", value: "40", label: "Romania +40" },
          { name: "Russia", value: "7", label: "Russia +7" },
          { name: "Rwanda", value: "250", label: "Rwanda +250" },
          { name: "Reunion", value: "262", label: "Reunion +262" },
          {
            name: "Saint Barthelemy",
            value: "590",
            label: "Saint Barthelemy +590"
          },
          {
            name: "Saint Helena, Ascension and Tristan Da Cunha",
            value: "290",
            label: "Saint Helena, Ascension and Tristan Da Cunha +290"
          },
          {
            name: "Saint Kitts and Nevis",
            value: "1869",
            label: "Saint Kitts and Nevis +1869"
          },
          { name: "Saint Lucia", value: "1758", label: "Saint Lucia +1758" },
          { name: "Saint Martin", value: "590", label: "Saint Martin +590" },
          {
            name: "Saint Pierre and Miquelon",
            value: "508",
            label: "Saint Pierre and Miquelon +508"
          },
          {
            name: "Saint Vincent and the Grenadines",
            value: "1784",
            label: "Saint Vincent and the Grenadines +1784"
          },
          { name: "Samoa", value: "685", label: "Samoa +685" },
          { name: "San Marino", value: "378", label: "San Marino +378" },
          {
            name: "Sao Tome and Principe",
            value: "239",
            label: "Sao Tome and Principe +239"
          },
          { name: "Saudi Arabia", value: "966", label: "Saudi Arabia +966" },
          { name: "Senegal", value: "221", label: "Senegal +221" },
          { name: "Serbia", value: "381", label: "Serbia +381" },
          { name: "Seychelles", value: "248", label: "Seychelles +248" },
          { name: "Sierra Leone", value: "232", label: "Sierra Leone +232" },
          { name: "Singapore", value: "65", label: "Singapore +65" },
          { name: "Slovakia", value: "421", label: "Slovakia +421" },
          { name: "Slovenia", value: "386", label: "Slovenia +386" },
          {
            name: "Solomon Islands",
            value: "677",
            label: "Solomon Islands +677"
          },
          { name: "Somalia", value: "252", label: "Somalia +252" },
          { name: "South Africa", value: "27", label: "South Africa +27" },
          { name: "South Sudan", value: "211", label: "South Sudan +211" },
          {
            name: "South Georgia and the South Sandwich Islands",
            value: "500",
            label: "South Georgia and the South Sandwich Islands +500"
          },
          { name: "Spain", value: "34", label: "Spain +34" },
          { name: "Sri Lanka", value: "94", label: "Sri Lanka +94" },
          { name: "Sudan", value: "249", label: "Sudan +249" },
          { name: "Suriname", value: "597", label: "Suriname +597" },
          {
            name: "Svalbard and Jan Mayen",
            value: "47",
            label: "Svalbard and Jan Mayen +47"
          },
          { name: "Swaziland", value: "268", label: "Swaziland +268" },
          { name: "Sweden", value: "46", label: "Sweden +46" },
          { name: "Switzerland", value: "41", label: "Switzerland +41" },
          {
            name: "Syrian Arab Republic",
            value: "963",
            label: "Syrian Arab Republic +963"
          },
          { name: "Taiwan", value: "886", label: "Taiwan +886" },
          { name: "Tajikistan", value: "992", label: "Tajikistan +992" },
          {
            name: "Tanzania, United Republic of Tanzania",
            value: "255",
            label: "Tanzania, United Republic of Tanzania +255"
          },
          { name: "Thailand", value: "66", label: "Thailand +66" },
          { name: "Timor-Leste", value: "670", label: "Timor-Leste +670" },
          { name: "Togo", value: "228", label: "Togo +228" },
          { name: "Tokelau", value: "690", label: "Tokelau +690" },
          { name: "Tonga", value: "676", label: "Tonga +676" },
          {
            name: "Trinidad and Tobago",
            value: "1868",
            label: "Trinidad and Tobago +1868"
          },
          { name: "Tunisia", value: "216", label: "Tunisia +216" },
          { name: "Turkey", value: "90", label: "Turkey +90" },
          { name: "Turkmenistan", value: "993", label: "Turkmenistan +993" },
          {
            name: "Turks and Caicos Islands",
            value: "1649",
            label: "Turks and Caicos Islands +1649"
          },
          { name: "Tuvalu", value: "688", label: "Tuvalu +688" },
          { name: "Uganda", value: "256", label: "Uganda +256" },
          { name: "Ukraine", value: "380", label: "Ukraine +380" },
          {
            name: "United Arab Emirates",
            value: "971",
            label: "United Arab Emirates +971"
          },
          { name: "United Kingdom", value: "44", label: "United Kingdom +44" },
          { name: "United States", value: "1", label: "United States +1" },
          { name: "Uruguay", value: "598", label: "Uruguay +598" },
          { name: "Uzbekistan", value: "998", label: "Uzbekistan +998" },
          { name: "Vanuatu", value: "678", label: "Vanuatu +678" },
          {
            name: "Venezuela, Bolivarian Republic of Venezuela",
            value: "58",
            label: "Venezuela, Bolivarian Republic of Venezuela +58"
          },
          { name: "Vietnam", value: "84", label: "Vietnam +84" },
          {
            name: "Virgin Islands, British",
            value: "1284",
            label: "Virgin Islands, British +1284"
          },
          {
            name: "Virgin Islands, U.S.",
            value: "1340",
            label: "Virgin Islands, U.S. +1340"
          },
          {
            name: "Wallis and Futuna",
            value: "681",
            label: "Wallis and Futuna +681"
          },
          { name: "Yemen", value: "967", label: "Yemen +967" },
          { name: "Zambia", value: "260", label: "Zambia +260" },
          { name: "Zimbabwe", value: "263", label: "Zimbabwe +263" }
        ]
      },
      {
        path: "uploadingImage",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    auth: usePlasmicDataOp(() => {
      return {
        sourceId: "bvg9JqrXbdUtvMXZbC26cd",
        opId: "49e98aef-cb8c-4949-b093-0798cb3267f2",
        userArgs: {
          headers: [`bearer ${localStorage.getItem("strapi-jwt")}`]
        },
        cacheKey: `plasmic.$.49e98aef-cb8c-4949-b093-0798cb3267f2.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    userInfo: usePlasmicDataOp(() => {
      return {
        sourceId: "bvg9JqrXbdUtvMXZbC26cd",
        opId: "be11c307-f463-4ebf-8aeb-bfa58a932c02",
        userArgs: {
          variables: [$queries.auth]
        },
        cacheKey: `plasmic.$.be11c307-f463-4ebf-8aeb-bfa58a932c02.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    enquiriesInfo: usePlasmicDataOp(() => {
      return {
        sourceId: "bvg9JqrXbdUtvMXZbC26cd",
        opId: "55121eb2-52ba-4a2a-8b85-78e3068be8b2",
        userArgs: {
          variables: [$queries.auth]
        },
        cacheKey: `plasmic.$.55121eb2-52ba-4a2a-8b85-78e3068be8b2.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <LayerDefault
            data-plasmic-name={"layerDefault"}
            data-plasmic-override={overrides.layerDefault}
            className={classNames("__wab_instance", sty.layerDefault)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "layerDefault"],
  layerDefault: ["layerDefault"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUserDashboard__ArgProps,
          internalVariantPropNames: PlasmicUserDashboard__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUserDashboard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserDashboard";
  } else {
    func.displayName = `PlasmicUserDashboard.${nodeName}`;
  }
  return func;
}

export const PlasmicUserDashboard = Object.assign(
  // Top-level PlasmicUserDashboard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    layerDefault: makeNodeComponent("layerDefault"),
    // Metadata about props expected for PlasmicUserDashboard
    internalVariantProps: PlasmicUserDashboard__VariantProps,
    internalArgProps: PlasmicUserDashboard__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicUserDashboard;
/* prettier-ignore-end */
