/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i8KuCHvKrwawZpBmyovrv7
// Component: 4Vh8-Nc4S1Td
import * as React from "react";
import {
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  set as $stateSet,
  useDollarState
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";
import { TabsContainer } from "@plasmicpkgs/plasmic-tabs";
import { TabContent } from "@plasmicpkgs/plasmic-tabs";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import Spinner from "../../Spinner"; // plasmic-import: mr_E4LUxuhwI/component
import { TabButton } from "@plasmicpkgs/plasmic-tabs";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { AntdPagination } from "@plasmicpkgs/antd5/skinny/registerPagination";
import { paginationHelpers as AntdPagination_Helpers } from "@plasmicpkgs/antd5/skinny/registerPagination";
import EnquiryForm from "../../EnquiryForm"; // plasmic-import: o-FKpOvt35MV/component
import { useScreenVariants as useScreenVariantszapf5SksSeNd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ZAPF5sksSeNd/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: i8KuCHvKrwawZpBmyovrv7/projectcss
import sty from "./PlasmicUserEnquiriesTable.module.css"; // plasmic-import: 4Vh8-Nc4S1Td/css
import ReviewsSvgIcon from "./icons/PlasmicIcon__ReviewsSvg"; // plasmic-import: GJ-OM5Ye5vqX/icon
import MessagesPeoplePersonBubble1Icon from "./icons/PlasmicIcon__MessagesPeoplePersonBubble1"; // plasmic-import: IdixEc2FgfFa/icon
import BackSvgrepoComSvgIcon from "./icons/PlasmicIcon__BackSvgrepoComSvg"; // plasmic-import: wpYSXM7SC3NG/icon

createPlasmicElementProxy;

export const PlasmicUserEnquiriesTable__VariantProps = new Array();

export const PlasmicUserEnquiriesTable__ArgProps = new Array("type", "userId");

const $$ = {};

function PlasmicUserEnquiriesTable__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "currentEnquiry",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => ({})
      },
      {
        path: "pagination.currentPage",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 1,
        onMutate: generateOnMutateForSpec("currentPage", AntdPagination_Helpers)
      },
      {
        path: "pagination.pageSize",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => 20,
        onMutate: generateOnMutateForSpec("pageSize", AntdPagination_Helpers)
      },
      {
        path: "pagination.startIndex",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("startIndex", AntdPagination_Helpers)
      },
      {
        path: "pagination.endIndex",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("endIndex", AntdPagination_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantszapf5SksSeNd()
  });
  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <TabsContainer
        data-plasmic-name={"tabsContainer"}
        data-plasmic-override={overrides.tabsContainer}
        initialKey={"inbox"}
        previewAll={false}
        previewKey={"inbox"}
      >
        <DataCtxReader__>
          {$ctx => (
            <div className={classNames(projectcss.all, sty.freeBox___6IJze)}>
              <TabContent
                data-plasmic-name={"inbox"}
                data-plasmic-override={overrides.inbox}
                className={classNames("__wab_instance", sty.inbox)}
                tabKey={"inbox"}
              >
                <Fetcher
                  data-plasmic-name={"enquiries"}
                  data-plasmic-override={overrides.enquiries}
                  dataOp={{
                    sourceId: "bvg9JqrXbdUtvMXZbC26cd",
                    opId: "c598c60a-471c-4182-97db-52e6be14099d",
                    userArgs: {
                      variables: [
                        $props.userId,
                        $props.type || "",
                        $state.pagination.currentPage,
                        $state.pagination.pageSize,
                        $props.userId
                      ]
                    },
                    cacheKey: `plasmic.$.m58ZmKfxDNiJ.$.c598c60a-471c-4182-97db-52e6be14099d.$.`,
                    invalidatedKeys: null,
                    roleId: null
                  }}
                  name={"enquiriesInfo"}
                  queries={{}}
                >
                  {$queries => (
                    <React.Fragment>
                      {(() => {
                        try {
                          return $queries.enquiriesInfo.isLoading;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <Spinner
                          data-plasmic-name={"spinner"}
                          data-plasmic-override={overrides.spinner}
                          className={classNames("__wab_instance", sty.spinner)}
                        />
                      ) : null}
                      {(() => {
                        try {
                          return !$queries.enquiriesInfo.isLoading;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return true;
                          }
                          throw e;
                        }
                      })() ? (
                        <Stack__
                          as={"div"}
                          data-plasmic-name={"grid"}
                          data-plasmic-override={overrides.grid}
                          hasGap={true}
                          className={classNames(projectcss.all, sty.grid)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__bqCy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__eevuy
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__mLHuI
                                )}
                              >
                                {"Event Date"}
                              </div>
                            </div>
                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return $queries.enquiriesInfo.data.response.data.enquiries.data.map(
                                    item => item.attributes
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_0, __plasmic_idx_0) => {
                              const currentItem = __plasmic_item_0;
                              const currentIndex = __plasmic_idx_0;
                              return (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__tcgfd
                                  )}
                                  key={currentIndex}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__hQmE7
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return new Date(
                                            currentItem.Date
                                          ).toLocaleDateString("en-US", {
                                            year: "numeric",
                                            month: "long",
                                            day: "numeric"
                                          });
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Event Date";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__eoJOf
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___2WsHu
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__dmTyM
                                )}
                              >
                                {"Budget"}
                              </div>
                            </div>
                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return $queries.enquiriesInfo.data.response.data.enquiries.data.map(
                                    item => item.attributes
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_0, __plasmic_idx_0) => {
                              const currentItem = __plasmic_item_0;
                              const currentIndex = __plasmic_idx_0;
                              return (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__d768X
                                  )}
                                  key={currentIndex}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___2MPx5
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return currentItem.Budget;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Event Type";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__l4LmY
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__qLlQn
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__jeOjr
                                )}
                              >
                                {"Event Location"}
                              </div>
                            </div>
                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return $queries.enquiriesInfo.data.response.data.enquiries.data.map(
                                    item => item.attributes
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_0, __plasmic_idx_0) => {
                              const currentItem = __plasmic_item_0;
                              const currentIndex = __plasmic_idx_0;
                              return (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__me7Ak
                                  )}
                                  key={currentIndex}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__nsIp6
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return currentItem?.location
                                            ?.Location;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Event Location";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__rt7Sl
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__paRns
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__keDrd
                                )}
                              >
                                {"Status"}
                              </div>
                            </div>
                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return $queries.enquiriesInfo.data.response.data.enquiries.data.map(
                                    item => item.attributes
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_0, __plasmic_idx_0) => {
                              const currentItem = __plasmic_item_0;
                              const currentIndex = __plasmic_idx_0;
                              return (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__pv9Fu
                                  )}
                                  key={currentIndex}
                                >
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___6Gl4
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return (() => {
                                            switch (currentItem.Status) {
                                              case "Lead":
                                                return "Pending";
                                              case "Prospect":
                                                return "Pending";
                                              case "FollowUp":
                                                return "Form Sent, Please Reply";
                                              case "Conversion":
                                                return "Accepted";
                                              case "Discarded":
                                                return "Denied";
                                              default:
                                                return "Some error occured. Please referesh or contact the admin";
                                            }
                                          })();
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Client Name";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__yKyG
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__vPdaM
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__xIodw
                                )}
                              >
                                {"Action"}
                              </div>
                            </div>
                            {(_par =>
                              !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                              (() => {
                                try {
                                  return $queries.enquiriesInfo.data.response.data.enquiries.data.map(
                                    item => {
                                      return {
                                        id: item.id,
                                        ...item.attributes
                                      };
                                    }
                                  );
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return [];
                                  }
                                  throw e;
                                }
                              })()
                            ).map((__plasmic_item_0, __plasmic_idx_0) => {
                              const currentItem = __plasmic_item_0;
                              const currentIndex = __plasmic_idx_0;
                              return (
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    sty.freeBox__lQv3T
                                  )}
                                  key={currentIndex}
                                >
                                  <Stack__
                                    as={"div"}
                                    hasGap={true}
                                    className={classNames(
                                      projectcss.all,
                                      sty.freeBox__gMr5V
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        sty.freeBox__c1B9Z
                                      )}
                                      onClick={async event => {
                                        const $steps = {};
                                        $steps["updateCurrentEnquiry"] = true
                                          ? (() => {
                                              const actionArgs = {
                                                variable: {
                                                  objRoot: $state,
                                                  variablePath: [
                                                    "currentEnquiry"
                                                  ]
                                                },
                                                operation: 1
                                              };
                                              return (({
                                                variable,
                                                value,
                                                startIndex,
                                                deleteCount
                                              }) => {
                                                if (!variable) {
                                                  return;
                                                }
                                                const {
                                                  objRoot,
                                                  variablePath
                                                } = variable;
                                                $stateSet(
                                                  objRoot,
                                                  variablePath,
                                                  undefined
                                                );
                                                return undefined;
                                              })?.apply(null, [actionArgs]);
                                            })()
                                          : undefined;
                                        if (
                                          $steps["updateCurrentEnquiry"] !=
                                            null &&
                                          typeof $steps[
                                            "updateCurrentEnquiry"
                                          ] === "object" &&
                                          typeof $steps["updateCurrentEnquiry"]
                                            .then === "function"
                                        ) {
                                          $steps["updateCurrentEnquiry"] =
                                            await $steps[
                                              "updateCurrentEnquiry"
                                            ];
                                        }
                                        $steps["graphqlQuery"] = true
                                          ? (() => {
                                              const actionArgs = {
                                                dataOp: {
                                                  sourceId:
                                                    "bvg9JqrXbdUtvMXZbC26cd",
                                                  opId: "938c07b5-b350-4ddf-9029-b77b11c2e7e0",
                                                  userArgs: {
                                                    variables: [currentItem.id]
                                                  },
                                                  cacheKey: null,
                                                  invalidatedKeys: null,
                                                  roleId: null
                                                }
                                              };
                                              return (async ({
                                                dataOp,
                                                continueOnError
                                              }) => {
                                                try {
                                                  const response =
                                                    await executePlasmicDataOp(
                                                      dataOp,
                                                      {
                                                        userAuthToken:
                                                          dataSourcesCtx?.userAuthToken,
                                                        user: dataSourcesCtx?.user
                                                      }
                                                    );
                                                  await plasmicInvalidate(
                                                    dataOp.invalidatedKeys
                                                  );
                                                  return response;
                                                } catch (e) {
                                                  if (!continueOnError) {
                                                    throw e;
                                                  }
                                                  return e;
                                                }
                                              })?.apply(null, [actionArgs]);
                                            })()
                                          : undefined;
                                        if (
                                          $steps["graphqlQuery"] != null &&
                                          typeof $steps["graphqlQuery"] ===
                                            "object" &&
                                          typeof $steps["graphqlQuery"].then ===
                                            "function"
                                        ) {
                                          $steps["graphqlQuery"] = await $steps[
                                            "graphqlQuery"
                                          ];
                                        }
                                        $steps["updateCurrentEnquiry3"] = true
                                          ? (() => {
                                              const actionArgs = {
                                                variable: {
                                                  objRoot: $state,
                                                  variablePath: [
                                                    "currentEnquiry"
                                                  ]
                                                },
                                                operation: 0,
                                                value:
                                                  $steps.graphqlQuery.data
                                                    .response.data.enquiry.data
                                              };
                                              return (({
                                                variable,
                                                value,
                                                startIndex,
                                                deleteCount
                                              }) => {
                                                if (!variable) {
                                                  return;
                                                }
                                                const {
                                                  objRoot,
                                                  variablePath
                                                } = variable;
                                                $stateSet(
                                                  objRoot,
                                                  variablePath,
                                                  value
                                                );
                                                return value;
                                              })?.apply(null, [actionArgs]);
                                            })()
                                          : undefined;
                                        if (
                                          $steps["updateCurrentEnquiry3"] !=
                                            null &&
                                          typeof $steps[
                                            "updateCurrentEnquiry3"
                                          ] === "object" &&
                                          typeof $steps["updateCurrentEnquiry3"]
                                            .then === "function"
                                        ) {
                                          $steps["updateCurrentEnquiry3"] =
                                            await $steps[
                                              "updateCurrentEnquiry3"
                                            ];
                                        }
                                      }}
                                    >
                                      <TabButton
                                        data-plasmic-name={"enquiryButton"}
                                        data-plasmic-override={
                                          overrides.enquiryButton
                                        }
                                        className={classNames(
                                          "__wab_instance",
                                          sty.enquiryButton
                                        )}
                                        tabKey={"enquiry"}
                                      >
                                        <AntdButton
                                          data-plasmic-name={"message"}
                                          data-plasmic-override={
                                            overrides.message
                                          }
                                          className={classNames(
                                            "__wab_instance",
                                            sty.message
                                          )}
                                          onClick={async () => {
                                            const $steps = {};
                                          }}
                                          size={"small"}
                                          type={"ghost"}
                                        >
                                          <ReviewsSvgIcon
                                            className={classNames(
                                              projectcss.all,
                                              sty.svg__m73M7
                                            )}
                                            role={"img"}
                                          />
                                        </AntdButton>
                                      </TabButton>
                                    </div>
                                    {(() => {
                                      try {
                                        return currentItem.forms.data[0].id;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return false;
                                        }
                                        throw e;
                                      }
                                    })() ? (
                                      <div
                                        className={classNames(
                                          projectcss.all,
                                          sty.freeBox__n7FQz
                                        )}
                                        onClick={async event => {
                                          const $steps = {};
                                          $steps["goToPage"] = true
                                            ? (() => {
                                                const actionArgs = {
                                                  destination: (() => {
                                                    try {
                                                      return (
                                                        `/form/` +
                                                        currentItem.forms
                                                          .data[0].id +
                                                        "?enquiry=" +
                                                        currentItem.id
                                                      );
                                                    } catch (e) {
                                                      if (
                                                        e instanceof
                                                          TypeError ||
                                                        e?.plasmicType ===
                                                          "PlasmicUndefinedDataError"
                                                      ) {
                                                        return undefined;
                                                      }
                                                      throw e;
                                                    }
                                                  })()
                                                };
                                                return (({ destination }) => {
                                                  if (
                                                    typeof destination ===
                                                      "string" &&
                                                    destination.startsWith("#")
                                                  ) {
                                                    document
                                                      .getElementById(
                                                        destination.substr(1)
                                                      )
                                                      .scrollIntoView({
                                                        behavior: "smooth"
                                                      });
                                                  } else {
                                                    location.assign(
                                                      destination
                                                    );
                                                  }
                                                })?.apply(null, [actionArgs]);
                                              })()
                                            : undefined;
                                          if (
                                            $steps["goToPage"] != null &&
                                            typeof $steps["goToPage"] ===
                                              "object" &&
                                            typeof $steps["goToPage"].then ===
                                              "function"
                                          ) {
                                            $steps["goToPage"] = await $steps[
                                              "goToPage"
                                            ];
                                          }
                                        }}
                                      >
                                        <AntdButton
                                          data-plasmic-name={"message2"}
                                          data-plasmic-override={
                                            overrides.message2
                                          }
                                          className={classNames(
                                            "__wab_instance",
                                            sty.message2
                                          )}
                                          onClick={async () => {
                                            const $steps = {};
                                          }}
                                          size={"small"}
                                          type={"ghost"}
                                        >
                                          <MessagesPeoplePersonBubble1Icon
                                            className={classNames(
                                              projectcss.all,
                                              sty.svg__fnMlW
                                            )}
                                            role={"img"}
                                          />
                                        </AntdButton>
                                      </div>
                                    ) : null}
                                  </Stack__>
                                </div>
                              );
                            })}
                          </div>
                        </Stack__>
                      ) : null}
                      {(() => {
                        const child$Props = {
                          className: classNames(
                            "__wab_instance",
                            sty.pagination
                          ),
                          current: generateStateValueProp($state, [
                            "pagination",
                            "currentPage"
                          ]),
                          defaultCurrent: 1,
                          defaultPageSize: 20,
                          onChange: async (...eventArgs) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "currentPage",
                              ["pagination", "currentPage"],
                              AntdPagination_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "startIndex",
                              ["pagination", "startIndex"],
                              AntdPagination_Helpers
                            ).apply(null, eventArgs);
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "endIndex",
                              ["pagination", "endIndex"],
                              AntdPagination_Helpers
                            ).apply(null, eventArgs);
                          },
                          onShowSizeChange: async (...eventArgs) => {
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "pageSize",
                              ["pagination", "pageSize"],
                              AntdPagination_Helpers
                            ).apply(null, eventArgs);
                          },
                          pageSize: generateStateValueProp($state, [
                            "pagination",
                            "pageSize"
                          ]),
                          pageSizeOptions: [
                            { pageSize: 10 },
                            { pageSize: 20 },
                            { pageSize: 50 },
                            { pageSize: 100 }
                          ],

                          total: (() => {
                            try {
                              return $queries.enquiriesInfo.data.response.data
                                .enquiries.meta.pagination.total;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "currentPage",
                              plasmicStateName: "pagination.currentPage"
                            },
                            {
                              name: "pageSize",
                              plasmicStateName: "pagination.pageSize"
                            },
                            {
                              name: "startIndex",
                              plasmicStateName: "pagination.startIndex"
                            },
                            {
                              name: "endIndex",
                              plasmicStateName: "pagination.endIndex"
                            }
                          ],

                          [],
                          AntdPagination_Helpers ?? {},
                          child$Props
                        );
                        return (
                          <AntdPagination
                            data-plasmic-name={"pagination"}
                            data-plasmic-override={overrides.pagination}
                            {...child$Props}
                          />
                        );
                      })()}
                    </React.Fragment>
                  )}
                </Fetcher>
              </TabContent>
              <TabContent
                data-plasmic-name={"enquiry"}
                data-plasmic-override={overrides.enquiry}
                className={classNames("__wab_instance", sty.enquiry)}
                tabKey={"enquiry"}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__vhm6N)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qorow)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__mzj60)}
                    >
                      <TabButton
                        data-plasmic-name={"back"}
                        data-plasmic-override={overrides.back}
                        className={classNames("__wab_instance", sty.back)}
                        tabKey={"inbox"}
                      >
                        <AntdButton
                          data-plasmic-name={"button"}
                          data-plasmic-override={overrides.button}
                          className={classNames("__wab_instance", sty.button)}
                          danger={true}
                          size={"small"}
                          type={"primary"}
                        >
                          <BackSvgrepoComSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__s3YCx
                            )}
                            role={"img"}
                          />
                        </AntdButton>
                      </TabButton>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__df27F
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return (
                                "Sent on " +
                                new Date(
                                  $state.currentEnquiry.attributes.createdAt
                                ).toLocaleDateString("en-GB")
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </Stack__>
                  </div>
                  <EnquiryForm
                    data-plasmic-name={"enquiryForm"}
                    data-plasmic-override={overrides.enquiryForm}
                    className={classNames("__wab_instance", sty.enquiryForm)}
                    enquiry={(() => {
                      try {
                        return $state.currentEnquiry;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    storeId={(() => {
                      try {
                        return $props.userId;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />
                </Stack__>
              </TabContent>
            </div>
          )}
        </DataCtxReader__>
      </TabsContainer>
    </Stack__>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "tabsContainer",
    "inbox",
    "enquiries",
    "spinner",
    "grid",
    "enquiryButton",
    "message",
    "message2",
    "pagination",
    "enquiry",
    "back",
    "button",
    "enquiryForm"
  ],

  tabsContainer: [
    "tabsContainer",
    "inbox",
    "enquiries",
    "spinner",
    "grid",
    "enquiryButton",
    "message",
    "message2",
    "pagination",
    "enquiry",
    "back",
    "button",
    "enquiryForm"
  ],

  inbox: [
    "inbox",
    "enquiries",
    "spinner",
    "grid",
    "enquiryButton",
    "message",
    "message2",
    "pagination"
  ],

  enquiries: [
    "enquiries",
    "spinner",
    "grid",
    "enquiryButton",
    "message",
    "message2",
    "pagination"
  ],

  spinner: ["spinner"],
  grid: ["grid", "enquiryButton", "message", "message2"],
  enquiryButton: ["enquiryButton", "message"],
  message: ["message"],
  message2: ["message2"],
  pagination: ["pagination"],
  enquiry: ["enquiry", "back", "button", "enquiryForm"],
  back: ["back", "button"],
  button: ["button"],
  enquiryForm: ["enquiryForm"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicUserEnquiriesTable__ArgProps,
          internalVariantPropNames: PlasmicUserEnquiriesTable__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicUserEnquiriesTable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUserEnquiriesTable";
  } else {
    func.displayName = `PlasmicUserEnquiriesTable.${nodeName}`;
  }
  return func;
}

export const PlasmicUserEnquiriesTable = Object.assign(
  // Top-level PlasmicUserEnquiriesTable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tabsContainer: makeNodeComponent("tabsContainer"),
    inbox: makeNodeComponent("inbox"),
    enquiries: makeNodeComponent("enquiries"),
    spinner: makeNodeComponent("spinner"),
    grid: makeNodeComponent("grid"),
    enquiryButton: makeNodeComponent("enquiryButton"),
    message: makeNodeComponent("message"),
    message2: makeNodeComponent("message2"),
    pagination: makeNodeComponent("pagination"),
    enquiry: makeNodeComponent("enquiry"),
    back: makeNodeComponent("back"),
    button: makeNodeComponent("button"),
    enquiryForm: makeNodeComponent("enquiryForm"),
    // Metadata about props expected for PlasmicUserEnquiriesTable
    internalVariantProps: PlasmicUserEnquiriesTable__VariantProps,
    internalArgProps: PlasmicUserEnquiriesTable__ArgProps
  }
);

export default PlasmicUserEnquiriesTable;
/* prettier-ignore-end */
